---
# 桥接接触传感器数据 (从 Gazebo 到 ROS 2)
- ros_topic_name: "/football/contacts" # 在 ROS 2 里，我们给它起个干净利落的名字
  gz_topic_name: "/world/RoboCup15MSL/model/football/link/chassis/sensor/contact_sensor/contact"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS

# 桥接足球的实时位置 (从 Gazebo 到 ROS 2)
- ros_topic_name: "/football/pose"
  gz_topic_name: "/model/football/pose"
  ros_type_name: "geometry_msgs/msg/PoseArray" # 如果你想获取位姿，这是常用的格式
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
# - ros_topic_name: "/football/cmd_vel"
#   gz_topic_name: "/model/football/cmd_vel"
#   ros_type_name: "geometry_msgs/msg/Twist"
#   gz_type_name: "gz.msgs.Twist"
#   direction: ROS_TO_GZ
